#!/usr/bin/env python3
"""SSZ P5 F2b: action-derived high-L mass closure audit.

Derives/tests the high-L central even-parity mass entries directly against the
unreduced Zhang--Kase action architecture after the exact H0/psi reduction.

Key point: M12 contains TWO different m1-like combinations.  The c4 sector
uses the printed m1-plus combination, while the dA0/v9 Schur-complement sector
uses the reflected m1-minus combination.  Collapsing them to one m1 is the
source of the previously persistent M12 mismatch.
"""
from pathlib import Path
import importlib.util
import numpy as np
import pandas as pd
from scipy.interpolate import CubicSpline

BASE = Path('/mnt/data')
COEFF = BASE/'ssz_p5_integrable_svt_unreduced_even_coefficients_2026-09-12.csv'
CE = BASE/'ssz_p5_F2b_central_c3_e3_SELECTED_REPRESENTATIVE_2026-09-15.csv'
REDUCER = BASE/'ssz_hybrid_jet_aware_constraint_reducer.py'

d = pd.read_csv(COEFF).copy()
ce = pd.read_csv(CE)
# c3,e3 are subleading in the high-L identities below; they are inserted only
# so the finite-L direct reducer can be evaluated as a convergence probe.
d['c3'] = ce.c3_selected.to_numpy(float)
d['e3'] = ce.e3_selected.to_numpy(float)

r = d.x.to_numpy(float)
u = d.u.to_numpy(float)
order = np.argsort(r)
rs = r[order]

def dr(y):
    y = np.asarray(y, float)
    sp = CubicSpline(rs, y[order])
    z = np.empty_like(y)
    z[order] = sp(rs, 1)
    return z

h = d.h.to_numpy(float)
Ap = d.A0prime.to_numpy(float)
phip = d.phiprime.to_numpy(float)
a4 = d.a4.to_numpy(float)
a6 = d.a6.to_numpy(float)
a9 = d.a9.to_numpy(float)
v1 = d.v1.to_numpy(float)
v4 = d.v4.to_numpy(float)
v5 = d.v5.to_numpy(float)
v6 = d.v6.to_numpy(float)
v8 = d.v8.to_numpy(float)
v9 = d.v9.to_numpy(float)
v13 = d.v13.to_numpy(float)
c4 = d.c4.to_numpy(float)
c5 = d.c5.to_numpy(float)
d2 = d.d2.to_numpy(float)
d3 = d.d3.to_numpy(float)
e4 = d.e4.to_numpy(float)

# Appendix-A identities used by the algebraic high-L reduction.
identity = pd.DataFrame([
    ['a3 + r a4', np.max(np.abs(d.a3.to_numpy(float) + r*a4))],
    ['a8 + a4/(2h)', np.max(np.abs(d.a8.to_numpy(float) + a4/(2*h)))],
    ['v2 - A0prime*v1', np.max(np.abs(d.v2.to_numpy(float) - Ap*v1))],
    ['v3 + A0prime*v1 + phiprime*v4/2 + r*v6',
     np.max(np.abs(d.v3.to_numpy(float) + Ap*v1 + .5*phip*v4 + r*v6))],
    ['v12 + v6/(2h)', np.max(np.abs(d.v12.to_numpy(float) + v6/(2*h)))],
], columns=['identity','max_abs_residual'])

# Two genuinely different m1-like combinations generated by different action
# sectors. z1 is their common non-v8 piece.
z1 = (a4 + r*a9 - .5*r*Ap*v6)*v6
m1_plus  =  r*a4*v8 + z1      # printed Eq.(90), correct in the c4 sector
m1_minus = -r*a4*v8 + z1      # generated in the dA0/v9 Schur sector
m2 = 2*c5*v1 + (Ap*v1 + .5*phip*v4)*v6
m3_plus = a4*dr(v1) + .5*Ap*v1*v6
m4 = 2*Ap*v1 + phip*v4
m5_minus = a4*v13 - a6*v6

# Action-derived leading high-L mass entries.
M11 = -r**2*v6**2/(4*v1)
M13 = -r*v6/2
M33 = -v1
M22 = e4 + 2*h*c4*a6/a4 - m5_minus**2/(4*a4**2*v9)

T_d3 = -r*d3/2
T_c4 = -h*c4*z1/(a4*v6)
T_m2 = -r*h*a6*m2/(2*a4*v1)
T_v5 = r*v5*v6/(4*v1)
T_A0 = -m1_minus*m5_minus/(4*a4**2*v9)
IBP_inside = (2*r*h*c4
              + r*(2*d2*v1-v4*v6)/(2*v1)
              + r*v6*m5_minus/(2*a4*v9))
T_IBP = .25*dr(IBP_inside)
M12 = T_d3 + T_c4 + T_m2 + T_v5 + T_A0 + T_IBP

M23 = (h*Ap*c4*v1/a4 + v5/2
       + m3_plus*m5_minus/(2*a4**2*v9)
       - h*a6*m4/(2*a4)
       - .25*dr(v4 + v1*m5_minus/(a4*v9)))

# Direct finite-L reducer, preserving exactly the same unreduced action route
# used in the earlier central mass audit.
spec = importlib.util.spec_from_file_location('red', REDUCER)
red = importlib.util.module_from_spec(spec)
spec.loader.exec_module(red)

def direct_mass(L):
    h0 = red.generalized_psi_h0_reduction(d, L, r_col='x')
    D = h0.D_h1_pivot.to_numpy(float)
    p = h0.p_a1_over_a3.to_numpy(float)
    q = h0.q_La4_over_a3.to_numpy(float)
    h0v = np.c_[-h0.C_H2/D, -h0.C_phi/D, -d.v2/D]
    h1v = np.c_[-d.a3/D, -h0.B_eff/D, np.zeros(len(d))]
    ep = np.array([1.,0.,0.]); ef = np.array([0.,1.,0.]); ev = np.array([0.,0.,1.])
    H0 = np.empty_like(h0v); H1 = np.empty_like(h1v)
    for i in range(len(d)):
        H0[i] = ep - q[i]*h0v[i]
        H1[i] = -q[i]*h1v[i] - p[i]*ef
    Hv = np.concatenate([H0,H1], axis=1)
    hv = np.concatenate([h0v,h1v], axis=1)
    v1p = dr(v1)
    Cs = np.zeros((len(d),6,6))
    def add(C,coef,a,b=None):
        if b is None: b=a
        C += .5*coef*(np.outer(a,b)+np.outer(b,a))
    for i,c in d.iterrows():
        C = np.zeros((6,6)); Hvec = Hv[i]; hvec = hv[i]
        ephi = np.r_[ef,np.zeros(3)]; ephip = np.r_[np.zeros(3),ef]
        eV = np.r_[ev,np.zeros(3)]; eVp = np.r_[np.zeros(3),ev]
        add(C,float(c.c2),Hvec,ephip)
        add(C,float(c.c3+L*c.c4),Hvec,ephi)
        add(C,L*float(c.c5),Hvec,hvec)
        add(C,float(c.c6),Hvec,Hvec)
        add(C,L*float(c.d2),hvec,ephip)
        add(C,L*float(c.d3),hvec,ephi)
        add(C,L*float(c.d4),hvec,hvec)
        add(C,float(c.e2),ephip,ephip)
        add(C,float(c.e3+L*c.e4),ephi,ephi)
        S0 = float(c.v3)*Hvec + float(c.v4)*ephip + float(c.v5)*ephi + L*float(c.v6)*hvec
        add(C,-float(c.v1),eV,eV); add(C,1.,eV,S0); add(C,-1/(4*float(c.v1)),S0,S0)
        J0 = (-2*v1p[i]*eV - 2*float(c.v1)*eVp
              + L*(float(c.v8)*hvec + float(c.v12)*Hvec + float(c.v13)*ephi))
        add(C,-1/(4*L*float(c.v9)),J0,J0)
        Cs[i] = C
    A = Cs[:,:3,:3]
    B = Cs[:,:3,3:]
    Bs = .5*(B + np.swapaxes(B,1,2))
    Bp = np.empty_like(Bs)
    for ia in range(3):
        for ib in range(3):
            Bp[:,ia,ib] = dr(Bs[:,ia,ib])
    return A-Bp

trusted = (u >= 0.612) & (u <= 0.708)
def rel(a,b):
    return np.abs(a-b)/np.maximum(1.0,np.abs(b))

rows=[]
last=None
for L in [1e5,1e6,1e7,1e8,1e9]:
    M = direct_mass(float(L)); last=M
    pairs = {
        'M11': (M[:,0,0], M11),
        'M12': (M[:,0,1], M12),
        'M13': (M[:,0,2], M13),
        'M22_over_L': (M[:,1,1]/L, M22),
        'M23': (M[:,1,2], M23),
        'M33': (M[:,2,2], M33),
    }
    row={'L':L}
    for name,(aa,bb) in pairs.items():
        er=rel(aa,bb)
        row[name+'_median_rel']=np.median(er[trusted])
        row[name+'_max_rel_trusted']=np.max(er[trusted])
    rows.append(row)
conv = pd.DataFrame(rows)

# Termwise pointwise audit at the largest L.
termwise = pd.DataFrame({
    'u':u,'x':r,
    'T_d3':T_d3,'T_c4':T_c4,'T_m2':T_m2,'T_v5':T_v5,
    'T_A0_Schur':T_A0,'T_IBP':T_IBP,
    'M12_action_formula':M12,
    'M12_direct_L1e9':last[:,0,1],
    'M12_abs_residual_L1e9':np.abs(last[:,0,1]-M12),
    'M12_rel_residual_L1e9':rel(last[:,0,1],M12),
    'm1_plus_c4_sector':m1_plus,
    'm1_minus_A0_sector':m1_minus,
    'm5_minus_action':m5_minus,
    'IBP_inside_action':IBP_inside,
})

identity.to_csv(BASE/'ssz_p5_F2b_appendix_identity_residuals_2026-09-15.csv', index=False)
conv.to_csv(BASE/'ssz_p5_F2b_action_highL_mass_convergence_2026-09-15.csv', index=False)
termwise.to_csv(BASE/'ssz_p5_F2b_M12_termwise_action_audit_2026-09-15.csv', index=False)

print('Appendix identities:')
print(identity.to_string(index=False))
print('\nHigh-L convergence on 0.612 <= u <= 0.708:')
print(conv.to_string(index=False))
print('\nM12 L=1e9 median/max rel:',
      np.median(termwise.loc[trusted,'M12_rel_residual_L1e9']),
      np.max(termwise.loc[trusted,'M12_rel_residual_L1e9']))
