"""Profile-aware unreduced even-parity Euler descriptor.

This module keeps the eight common even-parity fields

    (H0, H1, H2, h1, dphi, dA0, dA1, V)

until after the Euler operator has been assembled.  In particular it does not
form the deep-core generalized-psi / H0 Schur complement that is numerically
ill-conditioned for the P5 punctured core.

The input is the same 41-slot coefficient stream used by the direct reducer.
All radial product rules generated by integration by parts are retained with
JET9D8.  The result is a differential-algebraic (descriptor) operator rather
than a pre-eliminated KRGSM matrix.
"""
from __future__ import annotations

from math import comb
from typing import Dict, Iterable, Tuple

import numpy as np
import pandas as pd

from ssz_p5.jets.jet9d8 import profile_derivative

FIELDS = ("H0", "H1", "H2", "h1", "dphi", "dA0", "dA1", "V")
FI = {name: i for i, name in enumerate(FIELDS)}
SLOTS = (
    *[f"a{i}" for i in range(1, 10)],
    *[f"b{i}" for i in range(1, 6)],
    *[f"c{i}" for i in range(1, 7)],
    *[f"d{i}" for i in range(1, 5)],
    *[f"e{i}" for i in range(1, 5)],
    *[f"v{i}" for i in range(1, 14)],
)

# coefficient profile, field i, derivative i, field j, derivative j
ProfileTerm = Tuple[np.ndarray, int, Tuple[int, int], int, Tuple[int, int]]


def _deriv(r: np.ndarray, a: np.ndarray, order: int, window: int, degree: int) -> np.ndarray:
    if order == 0:
        return np.asarray(a, float)
    return profile_derivative(r, a, order, window, degree)


def _profile_terms(df: pd.DataFrame, L: float) -> list[ProfileTerm]:
    """Return the full common auxiliary-field action with profile coefficients."""
    missing = [k for k in SLOTS if k not in df.columns]
    if missing:
        raise KeyError(f"missing 41-slot coefficients: {missing}")
    q = {k: df[k].to_numpy(float) for k in SLOTS}
    n = len(df)
    out: list[ProfileTerm] = []

    def add(c, A, da=(0, 0), B=None, db=(0, 0)):
        if B is None:
            B = A
        cc = np.asarray(c, float)
        if cc.ndim == 0:
            cc = np.full(n, float(cc))
        if np.any(cc != 0.0):
            out.append((cc, FI[A], tuple(da), FI[B], tuple(db)))

    # Common unreduced Lu block.
    add(q["a1"], "H0", (0, 0), "dphi", (0, 2))
    add(q["a2"], "H0", (0, 0), "dphi", (0, 1))
    add(q["a3"], "H0", (0, 0), "H2", (0, 1))
    add(L * q["a4"], "H0", (0, 0), "h1", (0, 1))
    add(q["a5"] + L * q["a6"], "H0", (0, 0), "dphi", (0, 0))
    add(q["a7"] + L * q["a8"], "H0", (0, 0), "H2", (0, 0))
    add(L * q["a9"], "H0", (0, 0), "h1", (0, 0))
    add(L * q["b1"], "H1", (0, 0), "H1", (0, 0))
    add(q["b2"], "H1", (0, 0), "dphi", (1, 1))
    add(q["b3"], "H1", (0, 0), "dphi", (1, 0))
    add(q["b4"], "H1", (0, 0), "H2", (1, 0))
    add(L * q["b5"], "H1", (0, 0), "h1", (1, 0))
    add(q["c1"], "dphi", (1, 0), "H2", (1, 0))
    add(q["c2"], "H2", (0, 0), "dphi", (0, 1))
    add(q["c3"] + L * q["c4"], "H2", (0, 0), "dphi", (0, 0))
    add(L * q["c5"], "H2", (0, 0), "h1", (0, 0))
    add(q["c6"], "H2", (0, 0), "H2", (0, 0))
    add(L * q["d1"], "h1", (1, 0), "h1", (1, 0))
    add(L * q["d2"], "h1", (0, 0), "dphi", (0, 1))
    add(L * q["d3"], "h1", (0, 0), "dphi", (0, 0))
    add(L * q["d4"], "h1", (0, 0), "h1", (0, 0))
    add(q["e1"], "dphi", (1, 0), "dphi", (1, 0))
    add(q["e2"], "dphi", (0, 1), "dphi", (0, 1))
    add(q["e3"] + L * q["e4"], "dphi", (0, 0), "dphi", (0, 0))

    # Auxiliary-vector block.
    v1 = q["v1"]
    if np.any(np.abs(v1) < 1e-300):
        raise ZeroDivisionError("v1=0 in auxiliary-vector representation")
    add(2 * v1, "V", (0, 0), "dA0", (0, 1))
    add(-2 * v1, "V", (0, 0), "dA1", (1, 0))
    add(-v1, "V", (0, 0), "V", (0, 0))

    S = [
        (q["v2"], "H0", (0, 0)),
        (q["v3"], "H2", (0, 0)),
        (q["v4"], "dphi", (0, 1)),
        (q["v5"], "dphi", (0, 0)),
        (L * q["v6"], "h1", (0, 0)),
    ]
    for c, field, dd in S:
        add(c, "V", (0, 0), field, dd)
    for ia, (ca, fa, da) in enumerate(S):
        add(-ca * ca / (4 * v1), fa, da, fa, da)
        for cb, fb, db in S[ia + 1 :]:
            add(-ca * cb / (2 * v1), fa, da, fb, db)

    add(0.5 * L * q["v6"], "h1", (0, 0), "dA1", (1, 0))
    add(q["v7"], "H0", (0, 0), "H0", (0, 0))
    add(L * q["v8"], "h1", (0, 0), "dA0", (0, 0))
    add(L * q["v9"], "dA0", (0, 0), "dA0", (0, 0))
    add(L * q["v10"], "dA1", (0, 0), "dA1", (0, 0))
    add(L * q["v11"], "H1", (0, 0), "dA1", (0, 0))
    add(L * q["v12"], "H2", (0, 0), "dA0", (0, 0))
    add(L * q["v13"], "dphi", (0, 0), "dA0", (0, 0))
    return out


def _addop(dst: Dict[Tuple[int, int], np.ndarray], key, val) -> None:
    if key in dst:
        dst[key] += val
    else:
        dst[key] = np.array(val, dtype=float, copy=True)


def descriptor_operator(
    df: pd.DataFrame,
    L: float,
    window: int = 9,
    degree: int = 8,
) -> Dict[Tuple[int, int], np.ndarray]:
    """Assemble the 8x8 Euler differential operator before constraints.

    Returned keys are ``(time_derivative_order, radial_derivative_order)`` and
    values have shape ``(n_radius, 8, 8)``.
    """
    d = df.copy().reset_index(drop=True)
    if "x" not in d.columns:
        raise KeyError("descriptor requires radial column 'x'")
    r = d["x"].to_numpy(float)
    n = len(d)
    P: Dict[Tuple[int, int], np.ndarray] = {}

    def one_side(c, i, a, j, b):
        at, ar = a
        bt, br = b
        sign = (-1.0) ** (at + ar)
        for k in range(ar + 1):
            ck = _deriv(r, c, k, window, degree)
            key = (at + bt, ar - k + br)
            block = np.zeros((n, len(FIELDS), len(FIELDS)), float)
            block[:, i, j] = sign * comb(ar, k) * ck
            _addop(P, key, block)

    for c, i, a, j, b in _profile_terms(d, float(L)):
        one_side(c, i, a, j, b)
        one_side(c, j, b, i, a)
    return P


def evaluate_symbol(
    P: Dict[Tuple[int, int], np.ndarray],
    omega: complex,
    kr: complex,
    index: int | slice | None = None,
) -> np.ndarray:
    """Evaluate the descriptor for exp(-i omega t + i kr r)."""
    sample = next(iter(P.values()))
    n = sample.shape[0]
    out = np.zeros((n, len(FIELDS), len(FIELDS)), complex)
    dt = -1j * omega
    dr = 1j * kr
    for (pt, pr), a in P.items():
        out += a * (dt**pt) * (dr**pr)
    if index is None:
        return out
    return out[index]


def schur_symbol(
    symbol: np.ndarray,
    keep: Iterable[str] = ("H2", "dphi", "V"),
    rcond: float = 1e-13,
) -> tuple[np.ndarray, dict]:
    """Schur-reduce a local descriptor symbol without altering the action.

    This is intended as a *well-conditioned-region crosscheck*.  Deep-core use
    should keep the descriptor unreduced whenever the auxiliary pivot is badly
    conditioned.
    """
    A = np.asarray(symbol, complex)
    keep_idx = np.array([FI[x] for x in keep], int)
    aux_idx = np.array([i for i in range(len(FIELDS)) if i not in set(keep_idx)], int)
    Akk = A[np.ix_(keep_idx, keep_idx)]
    Aka = A[np.ix_(keep_idx, aux_idx)]
    Aak = A[np.ix_(aux_idx, keep_idx)]
    Aaa = A[np.ix_(aux_idx, aux_idx)]
    s = np.linalg.svd(Aaa, compute_uv=False)
    cond = float(np.inf if s[-1] == 0 else s[0] / s[-1])
    rank = int(np.sum(s > (s[0] * rcond if s.size else 0.0)))
    if rank < len(aux_idx):
        X = np.linalg.pinv(Aaa, rcond=rcond) @ Aak
        method = "pinv"
    else:
        X = np.linalg.solve(Aaa, Aak)
        method = "solve"
    return Akk - Aka @ X, {"aux_condition": cond, "aux_rank": rank, "method": method}


def structural_audit(P: Dict[Tuple[int, int], np.ndarray]) -> dict:
    """Basic exact-architecture diagnostics for a descriptor profile."""
    max_order = max((pt + pr for pt, pr in P), default=0)
    max_time = max((pt for pt, _ in P), default=0)
    max_radial = max((pr for _, pr in P), default=0)
    return {
        "fields": list(FIELDS),
        "operator_keys": [list(k) for k in sorted(P)],
        "max_total_derivative_order": int(max_order),
        "max_time_derivative_order": int(max_time),
        "max_radial_derivative_order": int(max_radial),
    }

PSI_FIELDS = ("psi", "dphi", "V", "h1", "H0", "H1", "dA0", "dA1")
PFI = {name: i for i, name in enumerate(PSI_FIELDS)}


def _add_rowop(dst, key, val):
    if key in dst:
        dst[key] += val
    else:
        dst[key] = np.array(val, float, copy=True)


def _apply_row_derivative(op, dt, dr, r, window, degree):
    out = {}
    for (pt, pr), a in op.items():
        for k in range(dr + 1):
            ak = _deriv(r, a, k, window, degree) if k else a
            _add_rowop(out, (pt + dt, pr + dr - k), comb(dr, k) * ak)
    return out


def generalized_psi_maps(df: pd.DataFrame, L: float) -> dict[str, dict[tuple[int, int], np.ndarray]]:
    """Original fields as differential rows on the constraint-preserving basis.

    The only nontrivial map is
        H2 = psi - q h1 - p dphi',
        p = a1/a3, q = L a4/a3.
    H0 and h1 are deliberately *not* eliminated.
    """
    n = len(df)
    z = np.zeros((n, len(PSI_FIELDS)), float)

    def basis(name):
        a = z.copy()
        a[:, PFI[name]] = 1.0
        return a

    a3 = df["a3"].to_numpy(float)
    if np.any(np.abs(a3) < 1e-300):
        raise ZeroDivisionError("a3=0 in generalized-psi map")
    p = df["a1"].to_numpy(float) / a3
    q = float(L) * df["a4"].to_numpy(float) / a3

    h2_0 = basis("psi") - q[:, None] * basis("h1")
    h2_1 = -p[:, None] * basis("dphi")
    return {
        "H0": {(0, 0): basis("H0")},
        "H1": {(0, 0): basis("H1")},
        "H2": {(0, 0): h2_0, (0, 1): h2_1},
        "h1": {(0, 0): basis("h1")},
        "dphi": {(0, 0): basis("dphi")},
        "dA0": {(0, 0): basis("dA0")},
        "dA1": {(0, 0): basis("dA1")},
        "V": {(0, 0): basis("V")},
    }


def _adjoint_rows(A, c, B, r, window, degree):
    n = len(r)
    out = {}
    for (pt, pr), av in A.items():
        for (qt, qr), bv in B.items():
            base = av[:, :, None] * bv[:, None, :] * c[:, None, None]
            sign = (-1.0) ** (pt + pr)
            for k in range(pr + 1):
                bk = _deriv(r, base, k, window, degree) if k else base
                _addop(out, (pt + qt, pr - k + qr), sign * comb(pr, k) * bk)
    return out


def generalized_psi_descriptor(
    df: pd.DataFrame,
    L: float,
    window: int = 9,
    degree: int = 8,
) -> Dict[Tuple[int, int], np.ndarray]:
    """Constraint-preserving 8x8 descriptor in the generalized-psi basis.

    Unlike the production 3-field reducer, this performs the safe differential
    change of variables but leaves the H0 multiplier and h1 constraint variable
    explicit.  It therefore avoids division by the deep-core ``D_h1`` pivot.
    """
    d = df.copy().reset_index(drop=True)
    # Keep the canonical v12 convention used by the direct reducer.
    if "h" in d.columns:
        d["v12"] = -d["v6"] / (2.0 * d["h"])
    r = d["x"].to_numpy(float)
    maps = generalized_psi_maps(d, float(L))
    P = {}
    for c, i, da, j, db in _profile_terms(d, float(L)):
        Aname, Bname = FIELDS[i], FIELDS[j]
        A = _apply_row_derivative(maps[Aname], da[0], da[1], r, window, degree)
        B = _apply_row_derivative(maps[Bname], db[0], db[1], r, window, degree)
        X = _adjoint_rows(A, c, B, r, window, degree)
        Y = _adjoint_rows(B, c, A, r, window, degree)
        for key, val in X.items():
            _addop(P, key, val)
        for key, val in Y.items():
            _addop(P, key, val)
    return P


def h0_constraint_structure(P: Dict[Tuple[int, int], np.ndarray]) -> dict:
    """Audit the generalized-psi H0 row before solving the constraint."""
    ih0 = PFI["H0"]
    idphi = PFI["dphi"]
    ih1 = PFI["h1"]
    forbidden = {}
    for key, block in P.items():
        pt, pr = key
        if pt != 0:
            val = np.max(np.abs(block[:, ih0, :]))
            if val:
                forbidden[f"time_{pt}_radial_{pr}"] = float(val)
        if pr >= 2:
            for name, j in (("dphi", idphi), ("h1", ih1)):
                val = float(np.max(np.abs(block[:, ih0, j])))
                if val:
                    forbidden[f"{name}_radial_{pr}"] = val
        if pr >= 1:
            val = float(np.max(np.abs(block[:, ih0, ih1])))
            if val:
                forbidden[f"h1_radial_{pr}"] = val
    return {
        "forbidden_terms": forbidden,
        "max_forbidden_abs": float(max(forbidden.values(), default=0.0)),
        "pass": bool(max(forbidden.values(), default=0.0) < 1e-8),
    }


def expected_h0_constraint_coefficients(
    df: pd.DataFrame,
    L: float,
    window: int = 9,
    degree: int = 8,
) -> dict[str, np.ndarray]:
    """JET9D8 version of the generalized-psi H0 constraint coefficients."""
    d = df.reset_index(drop=True)
    r = d["x"].to_numpy(float)
    qv = {k: d[k].to_numpy(float) for k in (
        "a1","a2","a3","a4","a5","a6","a7","a8","a9",
        "v1","v2","v3","v4","v5","v6",
    )}
    p = qv["a1"] / qv["a3"]
    q = float(L) * qv["a4"] / qv["a3"]
    pp = _deriv(r, p, 1, window, degree)
    qp = _deriv(r, q, 1, window, degree)
    B = qv["a2"] - qv["v2"] * qv["v4"] / (2.0 * qv["v1"])
    Cphi = qv["a5"] + float(L) * qv["a6"] - qv["v2"] * qv["v5"] / (2.0 * qv["v1"])
    CH2 = qv["a7"] + float(L) * qv["a8"] - qv["v2"] * qv["v3"] / (2.0 * qv["v1"])
    Ch1 = float(L) * (qv["a9"] - qv["v2"] * qv["v6"] / (2.0 * qv["v1"]))
    return {
        "a3": qv["a3"],
        "B_eff": B - qv["a3"] * pp - CH2 * p,
        "C_phi": Cphi,
        "C_H2": CH2,
        "D_h1": Ch1 - qv["a3"] * qp - CH2 * q,
        "v2": qv["v2"],
        "p": p,
        "q": q,
        "p_prime": pp,
        "q_prime": qp,
    }


def compare_h0_constraint(
    df: pd.DataFrame,
    L: float,
    P: Dict[Tuple[int, int], np.ndarray] | None = None,
    window: int = 9,
    degree: int = 8,
) -> dict:
    """Compare the descriptor H0 row with the closed JET9D8 formula."""
    if P is None:
        P = generalized_psi_descriptor(df, L, window, degree)
    n = len(df)
    z = np.zeros((n, len(PSI_FIELDS), len(PSI_FIELDS)))
    p01 = P.get((0, 1), z)
    p00 = P.get((0, 0), z)
    h = PFI["H0"]
    ref = expected_h0_constraint_coefficients(df, L, window, degree)
    pairs = {
        "a3_psi_prime": (p01[:, h, PFI["psi"]], ref["a3"]),
        "B_eff_dphi_prime": (p01[:, h, PFI["dphi"]], ref["B_eff"]),
        "C_phi_dphi": (p00[:, h, PFI["dphi"]], ref["C_phi"]),
        "C_H2_psi": (p00[:, h, PFI["psi"]], ref["C_H2"]),
        "D_h1_h1": (p00[:, h, PFI["h1"]], ref["D_h1"]),
        "v2_V": (p00[:, h, PFI["V"]], ref["v2"]),
    }
    out = {}
    for name, (got, want) in pairs.items():
        abs_err = np.abs(got - want)
        scale = np.maximum(1.0, np.abs(want))
        out[name] = {
            "max_abs": float(np.max(abs_err)),
            "max_scaled": float(np.max(abs_err / scale)),
        }
    out["H0_square_max_abs"] = float(np.max(np.abs(p00[:, h, h])))
    out["structure"] = h0_constraint_structure(P)
    out["pass"] = bool(
        out["structure"]["pass"]
        and out["H0_square_max_abs"] < 1e-8
        and max(v["max_scaled"] for k, v in out.items() if isinstance(v, dict) and "max_scaled" in v) < 1e-8
    )
    return out


def physical_reduction_maps(
    df: pd.DataFrame,
    L: float,
    window: int = 9,
    degree: int = 8,
) -> tuple[dict[str, dict[tuple[int, int], np.ndarray]], dict]:
    """Return the accepted differential map from the descriptor basis to y.

    The physical basis is ``y=(psi,dphi,V)``.  This is the same constraint map
    used by the established profile reducer, rewritten in the generalized-psi
    descriptor ordering.  ``H0`` maps to zero because its Euler equation is the
    multiplier constraint which has already been imposed by these maps.

    This helper is intended for *well-conditioned equivalence audits*.  It is
    not used in the deep core, where the point of the descriptor formulation is
    precisely to avoid the explicit ``D_h1`` inverse contained in these maps.
    """
    # Local import avoids a reducer -> numerics -> reducer import cycle.
    from ssz_p5.numerics import module

    d = df.copy().reset_index(drop=True)
    fm = module("ssz_hybrid_full_constraint_maps_JET9D8(1).py")
    try:
        m = fm.maps(d, float(L), window, degree)
    except FileNotFoundError:
        fm = module("ssz_hybrid_full_constraint_maps_JET9D8.py")
        m = fm.maps(d, float(L), window, degree)

    n = len(d)
    z = np.zeros((n, 3), float)

    def basis(j: int) -> np.ndarray:
        a = z.copy()
        a[:, j] = 1.0
        return a

    T = {
        "psi": {(0, 0): basis(0)},
        "dphi": {(0, 0): basis(1)},
        "V": {(0, 0): basis(2)},
        "h1": {(0, 0): m["H10"], (0, 1): m["H11"]},
        "H0": {},
        "H1": {(1, 0): m["H1dot0"], (1, 1): m["H1dot1"]},
        "dA0": {(0, 0): m["dA00"], (0, 1): m["dA01"]},
        "dA1": {(1, 0): m["dA1dot0"], (1, 1): m["dA1dot1"]},
    }
    return T, m


def pullback_descriptor(
    P: Dict[Tuple[int, int], np.ndarray],
    maps: dict[str, dict[tuple[int, int], np.ndarray]],
    r: np.ndarray,
    window: int = 9,
    degree: int = 8,
) -> Dict[Tuple[int, int], np.ndarray]:
    """Compute ``T^dagger P T`` as a 3-field differential operator.

    ``P`` is the generalized-psi descriptor Euler operator and ``maps`` is the
    differential map from its eight fields to ``y=(psi,dphi,V)``.  The product
    rules are evaluated with the same JET9D8 service as the production reducer.
    """
    rr = np.asarray(r, float)
    n = len(rr)

    # First U = P T.  Each U[field] is a scalar row differential operator on y.
    U: dict[str, dict[tuple[int, int], np.ndarray]] = {name: {} for name in PSI_FIELDS}
    for (pt, pr), block in P.items():
        for ia, aname in enumerate(PSI_FIELDS):
            for ib, bname in enumerate(PSI_FIELDS):
                coeff = block[:, ia, ib]
                if not np.any(coeff) or not maps[bname]:
                    continue
                for (qt, qr), row in maps[bname].items():
                    for k in range(pr + 1):
                        rk = _deriv(rr, row, k, window, degree) if k else row
                        val = coeff[:, None] * comb(pr, k) * rk
                        _add_rowop(U[aname], (pt + qt, pr - k + qr), val)

    # Then Q = T^dagger U.
    Q: Dict[Tuple[int, int], np.ndarray] = {}
    for name in PSI_FIELDS:
        for (pt, pr), trow in maps[name].items():
            sign = (-1.0) ** (pt + pr)
            for (qt, qr), urow in U[name].items():
                base = trow[:, :, None] * urow[:, None, :]
                for k in range(pr + 1):
                    bk = _deriv(rr, base, k, window, degree) if k else base
                    _addop(Q, (pt + qt, pr - k + qr), sign * comb(pr, k) * bk)
    return Q


def compare_descriptor_pullback(
    df: pd.DataFrame,
    L: float,
    window: int = 9,
    degree: int = 8,
) -> dict:
    """Cross-check the descriptor against the established 3-field reducer.

    This deliberately performs the comparison at the *differential-operator*
    level rather than by a naive pointwise Schur complement.  For a DAE with an
    H0 Lagrange multiplier those operations need not commute after numerical
    discretization.
    """
    from ssz_p5.numerics import module

    d = df.copy().reset_index(drop=True)
    P = generalized_psi_descriptor(d, float(L), window, degree)
    maps, _ = physical_reduction_maps(d, float(L), window, degree)
    got = pullback_descriptor(P, maps, d["x"].to_numpy(float), window, degree)
    reducer = module("ssz_p5_profile_operator_reducer_JET9D8_2026-09-16.py")
    ref, _, _ = reducer.reduced_operator(d, float(L), window, degree)

    n = len(d)
    keys = sorted(set(got) | set(ref))
    rows = {}
    for key in keys:
        a = got.get(key, np.zeros((n, 3, 3), float))
        b = ref.get(key, np.zeros((n, 3, 3), float))
        diff = a - b
        scaled = np.abs(diff) / np.maximum(1.0, np.abs(b))
        rows[str(key)] = {
            "max_scaled": float(np.max(scaled)),
            "p99_scaled": float(np.quantile(scaled, 0.99)),
            "relative_frobenius": float(np.linalg.norm(diff) / max(1.0, np.linalg.norm(b))),
        }

    principal_keys = [(2, 0), (2, 1), (2, 2), (0, 1), (0, 2)]
    principal_max = max(rows[str(k)]["max_scaled"] for k in principal_keys if str(k) in rows)
    p00_rel = rows.get(str((0, 0)), {}).get("relative_frobenius", 0.0)
    # Repeated JET application in the two algebraically equivalent paths is
    # expected to differ most in P00.  The gate therefore separates principal
    # identity from the lower-order roundoff diagnostic.
    passed = bool(principal_max < 1.0e-7 and p00_rel < 1.0e-6)
    return {
        "L": float(L),
        "operator_keys_descriptor_pullback": [list(k) for k in sorted(got)],
        "operator_keys_reference": [list(k) for k in sorted(ref)],
        "per_key": rows,
        "principal_max_scaled": float(principal_max),
        "P00_relative_frobenius": float(p00_rel),
        "pass": passed,
    }
