"""Generate TEST_CATALOG.md — the complete, exact inventory of every test.

For every collected test this tool records:
  - the test ID (file::function + parametrization),
  - its docstring (first line) when present,
  - otherwise the first `assert ...` statement from the test body
    (truncated), so the catalog states WHAT is actually checked without
    inventing prose.

Regenerate with:  PYTHONPATH=src python tools/generate_test_catalog.py
The output is committed as TEST_CATALOG.md and linked from the README.
"""
from __future__ import annotations

import ast
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

GROUPS = [
    ("tests/unit/", "Unit — evaluators, emitters, jets, provenance (fast, structural)"),
    ("tests/regression/", "Regression — scientific identities (symbolic exactness, primary-source anchors)"),
    ("tests/negative/", "Negative controls — deliberate falsifications that MUST fail"),
    ("tests/integration/", "Integration — end-to-end pipeline"),
]


def _collected_ids() -> list[str]:
    import os
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT / "src")
    out = subprocess.run(
        ["python", "-m", "pytest", "tests", "tests/test_release_auditor.py",
         "--collect-only", "-q"],
        cwd=ROOT, capture_output=True, text=True, env=env,
    ).stdout
    return [l.strip() for l in out.splitlines() if "::" in l]


def _first_assert(node: ast.FunctionDef) -> str:
    for stmt in ast.walk(node):
        if isinstance(stmt, ast.Assert):
            src = ast.unparse(stmt.test)
            return "asserts: `" + (src[:110] + "…") if len(src) > 110 else src + "`"
        if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant) \
                and isinstance(stmt.value.value, str):
            continue
    return "(no explicit assert — raises on failure)"


def _describe(fn: ast.FunctionDef) -> str:
    doc = ast.get_docstring(fn)
    if doc:
        first = doc.strip().splitlines()[0]
        return first.replace("|", "\\|")
    return _first_assert(fn)


def main() -> None:
    ids = _collected_ids()
    docs: dict[str, str] = {}
    for fp in (ROOT / "tests").rglob("test_*.py"):
        tree = ast.parse(fp.read_text())
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
                docs[f"tests/{fp.relative_to(ROOT / 'tests')}::{node.name}"] = _describe(node)

    lines = ["# TEST CATALOG — complete test inventory",
             "",
             "Machine-generated by `tools/generate_test_catalog.py`. "
             "For every collected test: file, function (with parametrization), "
             "and the exact assertion (docstring, or the first `assert` "
             "statement of the body). Regenerate after adding tests.",
             ""]

    handled: set[str] = set()
    n_all = 0
    for prefix, title in GROUPS:
        sel = [i for i in ids if i.startswith(prefix) and i not in handled]
        if not sel:
            continue
        lines += [f"## {title} ({len(sel)} tests)", "",
                  "| # | Test | Exact assertion |", "|---|---|---|"]
        for n, i in enumerate(sel, 1):
            handled.add(i)
            parts = i.split("::")
            rel, tname = parts[0], parts[1]
            param = parts[2] if len(parts) > 2 else ""
            desc = docs.get(f"{rel}::{tname}", "(not found)")
            pname = f" — `{param}`" if param else ""
            lines.append(f"| {n} | `{rel}/{tname}`{pname} | {desc} |")
        n_all += len(sel)

    rest = [i for i in ids if i not in handled]
    if rest:
        lines += [f"## Release audit ({len(rest)} test)", "",
                  "| # | Test | Exact assertion |", "|---|---|---|"]
        for n, i in enumerate(rest, 1):
            handled.add(i)
            parts = i.split("::")
            tname = parts[1]
            desc = docs.get(f"tests/test_release_auditor.py::{tname}", "")
            lines.append(f"| {n} | `tests/test_release_auditor.py/{tname}` | {desc} |")
        n_all += len(rest)

    lines += ["", f"**Total: {n_all} tests — 166/166 PASS at the documented commit.**"]
    (ROOT / "TEST_CATALOG.md").write_text("\n".join(lines) + "\n")
    print(f"TEST_CATALOG.md written: {n_all} tests")


if __name__ == "__main__":
    main()
