"""Background-null Horndeski tubular action controls.

The primary control implemented here is

    Delta G3(phi,X) = 1/2 q(phi) [X-X_b(phi)]^2.

On the selected one-dimensional background curve X=X_b(phi), Delta G3 and its
first action jets G3_X and G3_phi vanish identically.  Therefore the background
Maxwell--Horndeski equations are unchanged.  The second jets are nonzero and
supply an honest action-level normal direction for the even-parity coefficients
c2, c3 and e3.

The response follows Kase--Tsujikawa (2023), background Eqs. (7)--(16) and
Appendix-A c2,c3,e3.  Radial derivatives use the project's JET9D8 derivative
matrix, so this can be composed with the existing common-action solve without
introducing a second numerical differentiation convention.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
from scipy import sparse

from .holonomic_hessian_y import derivative_matrix


def g3_tubular_response_matrices(background: pd.DataFrame):
    """Return linear q(phi) -> {c2,c3,e3} response matrices.

    ``background`` must be ordered in increasing radial ``x`` and contain
    x,f,h,X.  ``phiprime`` is optional and is reconstructed on the negative P5
    branch when absent.

    The normal action section is Delta G3 = q(phi)(X-X_b(phi))^2/2.  On the
    curve, with X_phi=dX_b/dphi,

        G3_XX=q,  G3_phiX=-q X_phi,  G3_phiphi=q X_phi^2.

    Hence the response is exactly background-null at first-jet order.
    """
    d = background.copy().sort_values("x").reset_index(drop=True)
    r = d.x.to_numpy(float)
    f = d.f.to_numpy(float)
    h = d.h.to_numpy(float)
    X = d.X.to_numpy(float)
    if "phiprime" in d:
        ph = d.phiprime.to_numpy(float)
    else:
        ph = -np.sqrt(np.maximum(0.0, -2.0 * X / h))
    if np.any(f <= 0) or np.any(h <= 0) or np.any(np.abs(ph) < 1e-14):
        raise ValueError("G3 tubular response requires f,h>0 and nonzero phiprime")

    D = derivative_matrix(r)
    fp = np.asarray(D @ f).ravel()
    hp = np.asarray(D @ h).ravel()
    phipp = np.asarray(D @ ph).ravel()
    Xp = np.asarray(D @ X).ravel()
    Xphi = Xp / ph

    def diag(a):
        return sparse.diags(np.asarray(a, float), format="csr")

    # Mixed action jets of the exact tubular section.
    # A := G3_{phi X}, B := G3_{phi phi}.
    A = diag(-Xphi)
    B = diag(Xphi**2)

    # Only C1,C6,C9 acquire partial_phi responses; their background values are
    # unchanged because G3_X=G3_phi=0 on the curve.
    C1phi = diag(-h**2 * ph**2) @ A
    C6phi = diag(h * ph**2) @ B
    C9phi = C6phi

    E00phi = diag(phipp + ph * hp / (2.0 * h)) @ C1phi + C6phi
    E11phi = diag(-0.5 * ph * fp / f - 2.0 * ph / r) @ C1phi + C9phi
    E22phi = E00phi

    # Eq. (16), differentiated partially with respect to phi on the fixed
    # background.  Delta E_A0=0 for a pure G3 normal section.
    Ephi_phi = diag(-2.0 / ph) @ (
        diag(fp / (2.0 * f)) @ E00phi
        + D @ E11phi
        + diag(fp / (2.0 * f) + 2.0 / r) @ E11phi
        + diag(2.0 / r) @ E22phi
    )

    c3 = diag(-0.5 * np.sqrt(f) * r**2 / np.sqrt(h)) @ E11phi
    e3 = diag(0.25 * np.sqrt(f) * r**2 / np.sqrt(h)) @ Ephi_phi

    # Appendix-A c2 response for G3_X=G3_phi=0,
    # G3_XX=q and G3_phiX=-q X_phi.
    c2_coeff = np.sqrt(f * h) * (
        fp * h**2 * ph**4 * r**2 / (4.0 * f)
        + h**2 * ph**4 * r
        - 0.5 * h * Xphi * ph**3 * r**2
    )
    c2 = diag(c2_coeff)

    z = sparse.csr_matrix(c2.shape)
    return {
        "c2": c2.tocsr(),
        "c3": c3.tocsr(),
        "e3": e3.tocsr(),
        "v5": z,
        "v1": z,
        "v4": z,
    }


def g3_tubular_jets(background: pd.DataFrame, q) -> pd.DataFrame:
    """Emit the on-curve nonzero jets of the tubular G3 action section."""
    d = background.copy().sort_values("x").reset_index(drop=True)
    q = np.asarray(q, float)
    if q.shape != (len(d),):
        raise ValueError("q profile length mismatch")
    r = d.x.to_numpy(float)
    X = d.X.to_numpy(float)
    h = d.h.to_numpy(float)
    ph = d.phiprime.to_numpy(float) if "phiprime" in d else -np.sqrt(np.maximum(0.0, -2.0 * X / h))
    D = derivative_matrix(r)
    Xphi = np.asarray(D @ X).ravel() / ph
    return pd.DataFrame({
        "x": r,
        "G3_tubular": np.zeros(len(d)),
        "G3X_tubular": np.zeros(len(d)),
        "G3phi_tubular": np.zeros(len(d)),
        "G3XX_tubular": q,
        "G3phiX_tubular": -q * Xphi,
        "G3phiphi_tubular": q * Xphi**2,
    })


def g4xx_background_null_section(background: pd.DataFrame, q) -> pd.DataFrame:
    """Construct a holonomic quartic-Horndeski normal section preserving E00/E11/E22.

    The free normal profile is ``q = Delta G4_XX`` generated by
    ``Delta G4 = q(phi) (X-X_b(phi))^2/2``.  It is accompanied by a linear
    ``Delta G3 = p(phi)(X-X_b(phi))`` and by on-curve Delta G2 value/X-jet
    profiles solved pointwise so all three metric background equations vanish.
    The scalar equation then vanishes through the exact background identity
    when the vector equation is unchanged.

    This routine returns the compensating action jets and the induced primitive
    responses Delta a1 and Delta c4.  Tensor primitives F,G,H are unchanged.
    A c2 response is intentionally not fixed here: it can be cancelled exactly
    by the independent background-null G2_XX normal jet, whose nonzero Jacobian
    is exposed by ``mh_action_primitives.dc2_dG2XX``.
    """
    d = background.copy().sort_values("x").reset_index(drop=True)
    q = np.asarray(q, float)
    if q.shape != (len(d),):
        raise ValueError("q profile length mismatch")
    r=d.x.to_numpy(float); f=d.f.to_numpy(float); h=d.h.to_numpy(float); X=d.X.to_numpy(float)
    ph=d.phiprime.to_numpy(float) if "phiprime" in d else -np.sqrt(np.maximum(0.0,-2*X/h))
    D=derivative_matrix(r)
    fp=np.asarray(D@f).ravel(); hp=np.asarray(D@h).ravel(); fpp=np.asarray((D@D)@f).ravel(); phipp=np.asarray(D@ph).ravel(); Xp=np.asarray(D@X).ravel(); Xphi=Xp/ph

    def eoms(C1,C2,C4,C6,C7,C9):
        E00=(C1+C2/r)*phipp + (ph*C1/(2*h)+C4/r)*hp + C6+C7/r
        E11=-(ph*C1/(2*h)+C4/r)*h*fp/f + C9 -2*ph*C1/r -(ph*C2/(2*h)+(h-1)*C4)/r**2
        E22=(C2*fp/(4*f)+C1+C2/(2*r))*phipp \
             +(2*h*C4-ph*C2)/(4*f)*(fpp-fp**2/(2*f)) \
             +C4*fp*hp/(4*f) + C7*fp/(4*f) \
             +(ph*C1/h+C4/r)*hp/2 + C6+C7/(2*r)
        return E00,E11,E22

    z=np.zeros_like(r)
    # Unit responses for q, p, g0, gx.
    Eq=eoms(-2*h**2*Xphi*ph**2, 4*h**3*ph**3, 2*h**2*ph**4,
            -2*h*Xphi**2*ph**2, 4*h**2*Xphi*ph**3, z)
    Ep=eoms(-h**2*ph**2, z, z, -h*Xphi*ph**2, z, -h*Xphi*ph**2)
    Eg=eoms(z,z,z,np.ones_like(r),z,-np.ones_like(r))
    Ex=eoms(z,z,z,z,z,-h*ph**2)

    # Solve E00=E22=0 for p,g0 at unit q, then E11=0 for gx.
    det=Ep[0]*Eg[2]-Eg[0]*Ep[2]
    if np.min(np.abs(det)) < 1e-12:
        raise RuntimeError(f"quartic tubular background pivot too small: {np.min(np.abs(det))}")
    p_unit=(-Eq[0]*Eg[2]+Eg[0]*Eq[2])/det
    g_unit=(-Ep[0]*Eq[2]+Eq[0]*Ep[2])/det
    rem11=Eq[1]+p_unit*Ep[1]+g_unit*Eg[1]
    if np.min(np.abs(Ex[1])) < 1e-12:
        raise RuntimeError("G2X background pivot vanished")
    gx_unit=-rem11/Ex[1]

    p=p_unit*q; g0=g_unit*q; gx=gx_unit*q
    G4phiX=-q*Xphi; G4phiphi=q*Xphi**2
    G3phi=-p*Xphi
    # Holonomic G2_phi for a valid on-curve first jet section.
    g0p=np.asarray(D@g0).ravel()
    G2phi=(g0p-gx*Xp)/ph

    # Induced primitive responses, G5=0 and Delta G4=Delta G4X=Delta G4phi=0.
    sqfh=np.sqrt(f*h)
    da1=sqfh*(0.5*h*(p-2*G4phiX)*ph**2*r**2 - 2*h**2*q*ph**3*r)
    dc4=0.25*np.sqrt(f/h)*(
        (h*ph/f*(-2*h*q*ph**2))*fp
        +2*h*(p-2*G4phiX)*ph**2
        -4*h**2*q*ph**3/r
    )

    # Direct null audit with the solved amplitudes.
    E0=np.zeros_like(r); E1=np.zeros_like(r); E2=np.zeros_like(r)
    for coeff,resp in ((q,Eq),(p,Ep),(g0,Eg),(gx,Ex)):
        E0 += coeff*resp[0]; E1 += coeff*resp[1]; E2 += coeff*resp[2]

    return pd.DataFrame({
        "x":r,
        "q_G4XX":q,
        "delta_G4XX":q,
        "delta_G4phiX":G4phiX,
        "delta_G4phiphi":G4phiphi,
        "delta_G3X":p,
        "delta_G3phi":G3phi,
        "delta_G2":g0,
        "delta_G2X":gx,
        "delta_G2phi":G2phi,
        "delta_a1":da1,
        "delta_c4":dc4,
        "delta_E00":E0,
        "delta_E11":E1,
        "delta_E22":E2,
        "background_pivot":det,
    })
